spring.application.name: pf-sample
spring.profiles.active: local

server:
  port: 8090
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none


---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydatabase
    username: myuser
    password: secret

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        highlight_sql: true

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod
